FROM nginx:latest

COPY ./nginx.conf /etc/nginx/nginx.conf
COPY ./nginx.crt /etc/ssl/certs/nginx.crt
COPY ./nginx.key /etc/ssl/private/nginx.key

EXPOSE 80
EXPOSE 443

CMD ["nginx", "-g", "daemon off;"]
